# web server
nginx:
  image: nginx:1.15
  ports:
    - "80:80"
  volumes:
    - /Users/y/data/www:/usr/share/nginx/html:rw
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
  links:
    - fpm5:__DOCKER_PHP5_FPM__
    - fpm7:__DOCKER_PHP7_FPM__

# php-fpm
fpm5:
  build: ./php-fpm56
  ports:
    - "9000"
  volumes:
    - /Users/y/data/www:/usr/share/nginx/html:rw
    - ./php-fpm56/php.ini:/usr/local/etc/php/php.ini:ro

fpm7:
 build: ./php-fpm7
 ports:
   - 9000
 # links:
 #   - mysql:mysql
 volumes:
   - /Users/y/data/www:/usr/share/nginx/html:rw
   - ./php-fpm7/php.ini:/usr/local/etc/php/php.ini
   - ./php-fpm7/installer:/usr/installer
 environment:
   - CR_CENTER_DB=cr_center
   - CR_CENTER_HOST=10.10.112.236
   - CR_CENTER_USER=root
   - CR_CENTER_PASSWD=111222
   - CR_CENTER_PORT=3306
   - ES_HOST=es.d.gbicom.com:80
   - REDIS_HOST=10.10.112.195
   - REDIS_PORT=6379

# mysql:
#   image: mysql:5.7
#   ports:
#     - "3306:3306"
#   volumes:
#     - ./mysql:/var/lib/mysql
#   environment:
#     - MYSQL_ROOT_PASSWORD=111222

# redis:
#   image: redis:5.0
#   ports:
#     - "6379:6379"
# elasticsearch:
#   image: elasticsearch:5.6
#   ports:
#     - "9200:9200"