version: '3'
services:
  nginx:
    image: nginx:1.15
    ports:
      - "80:80"
    volumes:
      - ../www:/usr/share/nginx/html:rw
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro

  # php-fpm
  # fpm5:
  #   build: ./php-fpm56
  #   ports:
  #     - "9000"
  #   volumes:
  #     - /Users/y/data/www:/usr/share/nginx/html:rw
  #     - ./php-fpm56/php.ini:/usr/local/etc/php/php.ini:ro

  fpm7:
    build: ./php-fpm7
    ports:
      - 9000
    # links:
    #   - mysql:mysql
    volumes:
      - ../www:/usr/share/nginx/html:rw
      - ./php-fpm7/php.ini:/usr/local/etc/php/php.ini
      - ./php-fpm7/installer:/usr/installer

  # mysql:
  #   image: mysql:5.7
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ./mysql:/var/lib/mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=111222

  # redis:
  #   image: redis:5.0
  #   ports:
  #     - "6379:6379"
      