# web server
nginx:
  image: nginx:latest
  ports:
    - "80:80"
  volumes:
    # app
    - /home/www:/usr/share/nginx/html:rw
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
  links:
    - fpm5:__DOCKER_PHP_FPM__

# php-fpm
fpm5:
  build: ./php-fpm56
  ports:
    - "9000"
  volumes:
    - /home/www:/usr/share/nginx/html:rw
    # Your php.ini
    - ./php-fpm56/php.ini:/usr/local/etc/php/php.ini:ro
  # environment:
    # Set your APP env variables here:
    # - APP_KEY=
    # - DB_HOST=
    # - DB_DATABASE=
    # - DB_USERNAME=
    # - DB_PASSWORD=
  links:
    - mysql:mysql

# composer:
#   image: composer:1
#   volumes: 
#     - /home/www/tt/jwt:/app:rw
#   command: composer require lcobucci/jwt

# database
mysql:
  image: mysql:latest
  ports:
    - "3306:3306"
  volumes:
    - ./mysql:/var/lib/mysql:rw
  environment:
    - MYSQL_ROOT_PASSWORD=123456

